Improve lifecycle handling for Android, djinni update, fix clear of SymbolGroups when layers are updated
openmobilemaps/maps-core pull request #549
Opened 2023-11-22 15:52 UTC by maurhofer-ubique

2023-11-22 16:07 UTC, maerki approved these changes

2023-11-22 22:50 UTC, fbzli requested changes

2023-11-22 22:50 UTC, fbzli commented on android/src/main/java/io/openmobilemaps/mapscore/graphics/GLThread.kt
> +		}
sollte hier `isPaused` true sein, wird trotzdem ein Render Loop gemacht? Oder startet's gar nicht wenn's `isPaused` ist? Aber dann wäre der `if (!isPaused)` Check oben überflüssig.

2023-11-22 22:50 UTC, fbzli commented on android/src/main/java/io/openmobilemaps/mapscore/graphics/GLThread.kt
> +				} while (isPaused)
Solange `isPaused` ist, komme ich hier nicht aus dem Loop? Was wenn ich finishen will wenns paused ist wie z.B. `OffscreenMapRenderer.destroy()`?
Müsste evtl `while (isPaused && !finished)` sein?

2023-11-22 22:50 UTC, fbzli commented on android/src/main/java/io/openmobilemaps/mapscore/graphics/GLThread.kt
> +						wasPaused = true
Könnte ins `if` darüber.

2023-11-23 05:52 UTC, maurhofer-ubique commented on android/src/main/java/io/openmobilemaps/mapscore/graphics/GLThread.kt
> +		}
Habs etwas umstrukturiert 👍🏻

2023-11-23 05:52 UTC, maurhofer-ubique commented on android/src/main/java/io/openmobilemaps/mapscore/graphics/GLThread.kt
> +						wasPaused = true
Verstehe ich nicht ganz, was du meinst. Das wasPaused soll explizit ja erstmals nach dem Check gesetzt werden, damit das Callback nur ein Mal pro Pause (solange wir im do/while sind) invoked wird.

2023-11-23 05:52 UTC, maurhofer-ubique commented on android/src/main/java/io/openmobilemaps/mapscore/graphics/GLThread.kt
> +				} while (isPaused)
Guter Catch - ist angepasst 👍🏻

2023-11-23 06:53 UTC, maurhofer-ubique commented on android/src/main/java/io/openmobilemaps/mapscore/graphics/GLThread.kt
> +						wasPaused = true
Ah - du meinst die Condition an sich. Ist angepasst 👍🏻

2023-11-23 08:12 UTC, fbzli approved these changes

2023-11-23 09:14 UTC, merged